[workspace]
members = ["teacat_lib"]

[package]
name = "teacat"
version = "0.1.0"
edition = "2024"

[dependencies]
teacat_lib = { path = "teacat_lib" }
clap = { version = "4.5", features = ["cargo"] }
anyhow = "1"
anstyle = "1"
