[workspace]
members = ["webcat_lib"]

[package]
name = "webcat"
version = "0.1.0"
edition = "2024"

[dependencies]
webcat_lib = { path = "webcat_lib" }
clap = { version = "4.5", features = ["cargo"] }
anyhow = "1"
anstyle = "1"
